# Generated by Django 5.1.6 on 2025-03-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
